//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_Account_ent_Entry_FK1__Debit", "ent_Account", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wang.Velika.FamilyAccounting.BizLogic.Account), "ent_Entry", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.BizLogic.Entry))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_Account_ent_Entry_FK2__Credit", "ent_Account", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wang.Velika.FamilyAccounting.BizLogic.Account), "ent_Entry", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.BizLogic.Entry))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_AccountCategory_ent_Account_FK1", "ent_AccountCategory", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wang.Velika.FamilyAccounting.BizLogic.AccountCategory), "ent_Account", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.BizLogic.Account))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_AccountCategory_ent_AccountCategory_FK1", "ent_AccountCategory", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Wang.Velika.FamilyAccounting.BizLogic.AccountCategory), "ent_AccountCategory1", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.BizLogic.AccountCategory))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_EntryGroup_ent_Entry_FK1", "ent_EntryGroup", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wang.Velika.FamilyAccounting.BizLogic.EntryGroup), "ent_Entry", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.BizLogic.Entry))]

// Original file name:
// Generation date: 7/8/2009 3:49:11 PM
namespace Wang.Velika.FamilyAccounting.BizLogic
{
    
    /// <summary>
    /// There are no comments for EntitiesContext in the schema.
    /// </summary>
    public partial class EntitiesContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new EntitiesContext object using the connection string found in the 'EntitiesContext' section of the application configuration file.
        /// </summary>
        public EntitiesContext() : 
                base("name=EntitiesContext", "EntitiesContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new EntitiesContext object.
        /// </summary>
        public EntitiesContext(string connectionString) : 
                base(connectionString, "EntitiesContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new EntitiesContext object.
        /// </summary>
        public EntitiesContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "EntitiesContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for AccountSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Account> AccountSet
        {
            get
            {
                if ((this._AccountSet == null))
                {
                    this._AccountSet = base.CreateQuery<Account>("[AccountSet]");
                }
                return this._AccountSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Account> _AccountSet;
        /// <summary>
        /// There are no comments for AccountCategorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<AccountCategory> AccountCategorySet
        {
            get
            {
                if ((this._AccountCategorySet == null))
                {
                    this._AccountCategorySet = base.CreateQuery<AccountCategory>("[AccountCategorySet]");
                }
                return this._AccountCategorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AccountCategory> _AccountCategorySet;
        /// <summary>
        /// There are no comments for EntrySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Entry> EntrySet
        {
            get
            {
                if ((this._EntrySet == null))
                {
                    this._EntrySet = base.CreateQuery<Entry>("[EntrySet]");
                }
                return this._EntrySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Entry> _EntrySet;
        /// <summary>
        /// There are no comments for EntryGroupSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EntryGroup> EntryGroupSet
        {
            get
            {
                if ((this._EntryGroupSet == null))
                {
                    this._EntryGroupSet = base.CreateQuery<EntryGroup>("[EntryGroupSet]");
                }
                return this._EntryGroupSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EntryGroup> _EntryGroupSet;
        /// <summary>
        /// There are no comments for AccountSet in the schema.
        /// </summary>
        public void AddToAccountSet(Account account)
        {
            base.AddObject("AccountSet", account);
        }
        /// <summary>
        /// There are no comments for AccountCategorySet in the schema.
        /// </summary>
        public void AddToAccountCategorySet(AccountCategory accountCategory)
        {
            base.AddObject("AccountCategorySet", accountCategory);
        }
        /// <summary>
        /// There are no comments for EntrySet in the schema.
        /// </summary>
        public void AddToEntrySet(Entry entry)
        {
            base.AddObject("EntrySet", entry);
        }
        /// <summary>
        /// There are no comments for EntryGroupSet in the schema.
        /// </summary>
        public void AddToEntryGroupSet(EntryGroup entryGroup)
        {
            base.AddObject("EntryGroupSet", entryGroup);
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.BizLogic.Account in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.BizLogic", Name="Account")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Account : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Account object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="code">Initial value of Code.</param>
        /// <param name="balance">Initial value of Balance.</param>
        public static Account CreateAccount(int id, string name, string code, int balance)
        {
            Account account = new Account();
            account.ID = id;
            account.Name = name;
            account.Code = code;
            account.Balance = balance;
            return account;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this.ReportPropertyChanging("Code");
                this._Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Code");
                this.OnCodeChanged();
            }
        }
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property CommonDirectionRaw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Nullable<byte> CommonDirectionRaw
        {
            get
            {
                return this._CommonDirectionRaw;
            }
            set
            {
                this.OnCommonDirectionRawChanging(value);
                this.ReportPropertyChanging("CommonDirectionRaw");
                this._CommonDirectionRaw = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CommonDirectionRaw");
                this.OnCommonDirectionRawChanged();
            }
        }
        private global::System.Nullable<byte> _CommonDirectionRaw;
        partial void OnCommonDirectionRawChanging(global::System.Nullable<byte> value);
        partial void OnCommonDirectionRawChanged();
        /// <summary>
        /// There are no comments for Property Balance in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Balance
        {
            get
            {
                return this._Balance;
            }
            set
            {
                this.OnBalanceChanging(value);
                this.ReportPropertyChanging("Balance");
                this._Balance = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Balance");
                this.OnBalanceChanged();
            }
        }
        private int _Balance;
        partial void OnBalanceChanging(int value);
        partial void OnBalanceChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for DebitEntries in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_Account_ent_Entry_FK1__Debit", "ent_Entry")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Entry> DebitEntries
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Entry>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK1__Debit", "ent_Entry");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Entry>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK1__Debit", "ent_Entry", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for CreditEntryies in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_Account_ent_Entry_FK2__Credit", "ent_Entry")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Entry> CreditEntryies
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Entry>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK2__Credit", "ent_Entry");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Entry>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK2__Credit", "ent_Entry", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_AccountCategory_ent_Account_FK1", "ent_AccountCategory")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public AccountCategory Category
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AccountCategory>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_Account_FK1", "ent_AccountCategory").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AccountCategory>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_Account_FK1", "ent_AccountCategory").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<AccountCategory> CategoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AccountCategory>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_Account_FK1", "ent_AccountCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<AccountCategory>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_Account_FK1", "ent_AccountCategory", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.BizLogic.AccountCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.BizLogic", Name="AccountCategory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class AccountCategory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new AccountCategory object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="code">Initial value of Code.</param>
        public static AccountCategory CreateAccountCategory(int id, string name, string code)
        {
            AccountCategory accountCategory = new AccountCategory();
            accountCategory.ID = id;
            accountCategory.Name = name;
            accountCategory.Code = code;
            return accountCategory;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this.ReportPropertyChanging("Code");
                this._Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Code");
                this.OnCodeChanged();
            }
        }
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property DefaultDirectionRaw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Nullable<byte> DefaultDirectionRaw
        {
            get
            {
                return this._DefaultDirectionRaw;
            }
            set
            {
                this.OnDefaultDirectionRawChanging(value);
                this.ReportPropertyChanging("DefaultDirectionRaw");
                this._DefaultDirectionRaw = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DefaultDirectionRaw");
                this.OnDefaultDirectionRawChanged();
            }
        }
        private global::System.Nullable<byte> _DefaultDirectionRaw;
        partial void OnDefaultDirectionRawChanging(global::System.Nullable<byte> value);
        partial void OnDefaultDirectionRawChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for DirectAccounts in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_AccountCategory_ent_Account_FK1", "ent_Account")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Account> DirectAccounts
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Account>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_Account_FK1", "ent_Account");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Account>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_Account_FK1", "ent_Account", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for SubCategories in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_AccountCategory_ent_AccountCategory_FK1", "ent_AccountCategory1")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<AccountCategory> SubCategories
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<AccountCategory>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_AccountCategory_FK1" +
                        "", "ent_AccountCategory1");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<AccountCategory>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_AccountCategory_FK1" +
                            "", "ent_AccountCategory1", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ParentCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_AccountCategory_ent_AccountCategory_FK1", "ent_AccountCategory")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public AccountCategory ParentCategory
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AccountCategory>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_AccountCategory_FK1" +
                        "", "ent_AccountCategory").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AccountCategory>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_AccountCategory_FK1" +
                        "", "ent_AccountCategory").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ParentCategory in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<AccountCategory> ParentCategoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AccountCategory>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_AccountCategory_FK1" +
                        "", "ent_AccountCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<AccountCategory>("Wang.Velika.FamilyAccounting.BizLogic.ent_AccountCategory_ent_AccountCategory_FK1" +
                            "", "ent_AccountCategory", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.BizLogic.Entry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.BizLogic", Name="Entry")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Entry : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Entry object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="amount">Initial value of Amount.</param>
        public static Entry CreateEntry(int id, int amount)
        {
            Entry entry = new Entry();
            entry.ID = id;
            entry.Amount = amount;
            return entry;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Amount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnAmountChanging(value);
                this.ReportPropertyChanging("Amount");
                this._Amount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Amount");
                this.OnAmountChanged();
            }
        }
        private int _Amount;
        partial void OnAmountChanging(int value);
        partial void OnAmountChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for DebitAccount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_Account_ent_Entry_FK1__Debit", "ent_Account")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Account DebitAccount
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK1__Debit", "ent_Account").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK1__Debit", "ent_Account").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for DebitAccount in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Account> DebitAccountReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK1__Debit", "ent_Account");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Account>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK1__Debit", "ent_Account", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for CreditAccount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_Account_ent_Entry_FK2__Credit", "ent_Account")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Account CreditAccount
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK2__Credit", "ent_Account").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK2__Credit", "ent_Account").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CreditAccount in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Account> CreditAccountReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Account>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK2__Credit", "ent_Account");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Account>("Wang.Velika.FamilyAccounting.BizLogic.ent_Account_ent_Entry_FK2__Credit", "ent_Account", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_EntryGroup_ent_Entry_FK1", "ent_EntryGroup")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public EntryGroup Group
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntryGroup>("Wang.Velika.FamilyAccounting.BizLogic.ent_EntryGroup_ent_Entry_FK1", "ent_EntryGroup").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntryGroup>("Wang.Velika.FamilyAccounting.BizLogic.ent_EntryGroup_ent_Entry_FK1", "ent_EntryGroup").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<EntryGroup> GroupReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntryGroup>("Wang.Velika.FamilyAccounting.BizLogic.ent_EntryGroup_ent_Entry_FK1", "ent_EntryGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<EntryGroup>("Wang.Velika.FamilyAccounting.BizLogic.ent_EntryGroup_ent_Entry_FK1", "ent_EntryGroup", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.BizLogic.EntryGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.BizLogic", Name="EntryGroup")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EntryGroup : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EntryGroup object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="occurrenceTimestamp">Initial value of OccurrenceTimestamp.</param>
        public static EntryGroup CreateEntryGroup(int id, global::System.DateTime occurrenceTimestamp)
        {
            EntryGroup entryGroup = new EntryGroup();
            entryGroup.ID = id;
            entryGroup.OccurrenceTimestamp = occurrenceTimestamp;
            return entryGroup;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property OccurrenceTimestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime OccurrenceTimestamp
        {
            get
            {
                return this._OccurrenceTimestamp;
            }
            set
            {
                this.OnOccurrenceTimestampChanging(value);
                this.ReportPropertyChanging("OccurrenceTimestamp");
                this._OccurrenceTimestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OccurrenceTimestamp");
                this.OnOccurrenceTimestampChanged();
            }
        }
        private global::System.DateTime _OccurrenceTimestamp;
        partial void OnOccurrenceTimestampChanging(global::System.DateTime value);
        partial void OnOccurrenceTimestampChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Entries in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.BizLogic", "ent_EntryGroup_ent_Entry_FK1", "ent_Entry")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Entry> Entries
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Entry>("Wang.Velika.FamilyAccounting.BizLogic.ent_EntryGroup_ent_Entry_FK1", "ent_Entry");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Entry>("Wang.Velika.FamilyAccounting.BizLogic.ent_EntryGroup_ent_Entry_FK1", "ent_Entry", value);
                }
            }
        }
    }
}
