//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EntityProperty_met_EntityProperty_FK1", "met_EntityProperty", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EntityPropertyInfo), "met_EntityProperty1", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EntityPropertyInfo))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EntityType_met_EntityProperty_FK1", "met_EntityType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EntityTypeInfo), "met_EntityProperty", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EntityPropertyInfo))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EntityType_met_EntityProperty_FK2", "met_EntityType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EntityTypeInfo), "met_EntityProperty", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EntityPropertyInfo))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EnumerationType_met_EntityProperty_FK1", "met_EnumerationType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EnumerationTypeInfo), "met_EntityProperty", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EntityPropertyInfo))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EnumerationType_met_EnumerationItem_FK1", "met_EnumerationType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EnumerationTypeInfo), "met_EnumerationItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EnumerationItemInfo))]

// Original file name:
// Generation date: 2009-9-27 22:41:11
namespace Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata
{
    
    /// <summary>
    /// There are no comments for EntityMetadataContext in the schema.
    /// </summary>
    public partial class EntityMetadataContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new EntityMetadataContext object using the connection string found in the 'EntityMetadataContext' section of the application configuration file.
        /// </summary>
        public EntityMetadataContext() : 
                base("name=EntityMetadataContext", "EntityMetadataContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new EntityMetadataContext object.
        /// </summary>
        public EntityMetadataContext(string connectionString) : 
                base(connectionString, "EntityMetadataContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new EntityMetadataContext object.
        /// </summary>
        public EntityMetadataContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "EntityMetadataContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for EntityPropertyInfoSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EntityPropertyInfo> EntityPropertyInfoSet
        {
            get
            {
                if ((this._EntityPropertyInfoSet == null))
                {
                    this._EntityPropertyInfoSet = base.CreateQuery<EntityPropertyInfo>("[EntityPropertyInfoSet]");
                }
                return this._EntityPropertyInfoSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EntityPropertyInfo> _EntityPropertyInfoSet;
        /// <summary>
        /// There are no comments for EntityTypeInfoSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EntityTypeInfo> EntityTypeInfoSet
        {
            get
            {
                if ((this._EntityTypeInfoSet == null))
                {
                    this._EntityTypeInfoSet = base.CreateQuery<EntityTypeInfo>("[EntityTypeInfoSet]");
                }
                return this._EntityTypeInfoSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EntityTypeInfo> _EntityTypeInfoSet;
        /// <summary>
        /// There are no comments for EnumerationItemInfoSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EnumerationItemInfo> EnumerationItemInfoSet
        {
            get
            {
                if ((this._EnumerationItemInfoSet == null))
                {
                    this._EnumerationItemInfoSet = base.CreateQuery<EnumerationItemInfo>("[EnumerationItemInfoSet]");
                }
                return this._EnumerationItemInfoSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EnumerationItemInfo> _EnumerationItemInfoSet;
        /// <summary>
        /// There are no comments for EnumerationTypeInfoSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EnumerationTypeInfo> EnumerationTypeInfoSet
        {
            get
            {
                if ((this._EnumerationTypeInfoSet == null))
                {
                    this._EnumerationTypeInfoSet = base.CreateQuery<EnumerationTypeInfo>("[EnumerationTypeInfoSet]");
                }
                return this._EnumerationTypeInfoSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EnumerationTypeInfo> _EnumerationTypeInfoSet;
        /// <summary>
        /// There are no comments for EntityPropertyInfoSet in the schema.
        /// </summary>
        public void AddToEntityPropertyInfoSet(EntityPropertyInfo entityPropertyInfo)
        {
            base.AddObject("EntityPropertyInfoSet", entityPropertyInfo);
        }
        /// <summary>
        /// There are no comments for EntityTypeInfoSet in the schema.
        /// </summary>
        public void AddToEntityTypeInfoSet(EntityTypeInfo entityTypeInfo)
        {
            base.AddObject("EntityTypeInfoSet", entityTypeInfo);
        }
        /// <summary>
        /// There are no comments for EnumerationItemInfoSet in the schema.
        /// </summary>
        public void AddToEnumerationItemInfoSet(EnumerationItemInfo enumerationItemInfo)
        {
            base.AddObject("EnumerationItemInfoSet", enumerationItemInfo);
        }
        /// <summary>
        /// There are no comments for EnumerationTypeInfoSet in the schema.
        /// </summary>
        public void AddToEnumerationTypeInfoSet(EnumerationTypeInfo enumerationTypeInfo)
        {
            base.AddObject("EnumerationTypeInfoSet", enumerationTypeInfo);
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EntityPropertyInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", Name="EntityPropertyInfo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EntityPropertyInfo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EntityPropertyInfo object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="required">Initial value of Required.</param>
        public static EntityPropertyInfo CreateEntityPropertyInfo(int id, string name, bool required)
        {
            EntityPropertyInfo entityPropertyInfo = new EntityPropertyInfo();
            entityPropertyInfo.ID = id;
            entityPropertyInfo.Name = name;
            entityPropertyInfo.Required = required;
            return entityPropertyInfo;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property TargetKindRaw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private byte TargetKindRaw
        {
            get
            {
                return this._TargetKindRaw;
            }
            set
            {
                this.OnTargetKindRawChanging(value);
                this.ReportPropertyChanging("TargetKindRaw");
                this._TargetKindRaw = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TargetKindRaw");
                this.OnTargetKindRawChanged();
            }
        }
        private byte _TargetKindRaw;
        partial void OnTargetKindRawChanging(byte value);
        partial void OnTargetKindRawChanged();
        /// <summary>
        /// There are no comments for Property ColumnName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnName
        {
            get
            {
                return this._ColumnName;
            }
            set
            {
                this.OnColumnNameChanging(value);
                this.ReportPropertyChanging("ColumnName");
                this._ColumnName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ColumnName");
                this.OnColumnNameChanged();
            }
        }
        private string _ColumnName;
        partial void OnColumnNameChanging(string value);
        partial void OnColumnNameChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property Required in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Required
        {
            get
            {
                return this._Required;
            }
            set
            {
                this.OnRequiredChanging(value);
                this.ReportPropertyChanging("Required");
                this._Required = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Required");
                this.OnRequiredChanged();
            }
        }
        private bool _Required;
        partial void OnRequiredChanging(bool value);
        partial void OnRequiredChanged();
        /// <summary>
        /// There are no comments for Property RelationshipName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationshipName
        {
            get
            {
                return this._RelationshipName;
            }
            set
            {
                this.OnRelationshipNameChanging(value);
                this.ReportPropertyChanging("RelationshipName");
                this._RelationshipName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RelationshipName");
                this.OnRelationshipNameChanged();
            }
        }
        private string _RelationshipName;
        partial void OnRelationshipNameChanging(string value);
        partial void OnRelationshipNameChanged();
        /// <summary>
        /// There are no comments for OfOppositeProperties in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EntityProperty_met_EntityProperty_FK1", "met_EntityProperty1")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<EntityPropertyInfo> OfOppositeProperties
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityPrope" +
                        "rty_met_EntityProperty_FK1", "met_EntityProperty1");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityPrope" +
                            "rty_met_EntityProperty_FK1", "met_EntityProperty1", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for OppositeProperty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EntityProperty_met_EntityProperty_FK1", "met_EntityProperty")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public EntityPropertyInfo OppositeProperty
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityPrope" +
                        "rty_met_EntityProperty_FK1", "met_EntityProperty").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityPrope" +
                        "rty_met_EntityProperty_FK1", "met_EntityProperty").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for OppositeProperty in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<EntityPropertyInfo> OppositePropertyReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityPrope" +
                        "rty_met_EntityProperty_FK1", "met_EntityProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityPrope" +
                            "rty_met_EntityProperty_FK1", "met_EntityProperty", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Entity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EntityType_met_EntityProperty_FK1", "met_EntityType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public EntityTypeInfo Entity
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntityTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                        "met_EntityProperty_FK1", "met_EntityType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntityTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                        "met_EntityProperty_FK1", "met_EntityType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Entity in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<EntityTypeInfo> EntityReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntityTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                        "met_EntityProperty_FK1", "met_EntityType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<EntityTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                            "met_EntityProperty_FK1", "met_EntityType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TargetEntity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EntityType_met_EntityProperty_FK2", "met_EntityType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public EntityTypeInfo TargetEntity
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntityTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                        "met_EntityProperty_FK2", "met_EntityType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntityTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                        "met_EntityProperty_FK2", "met_EntityType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for TargetEntity in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<EntityTypeInfo> TargetEntityReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EntityTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                        "met_EntityProperty_FK2", "met_EntityType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<EntityTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                            "met_EntityProperty_FK2", "met_EntityType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TargetEnumeration in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EnumerationType_met_EntityProperty_FK1", "met_EnumerationType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public EnumerationTypeInfo TargetEnumeration
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EnumerationTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                        "Type_met_EntityProperty_FK1", "met_EnumerationType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EnumerationTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                        "Type_met_EntityProperty_FK1", "met_EnumerationType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for TargetEnumeration in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<EnumerationTypeInfo> TargetEnumerationReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EnumerationTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                        "Type_met_EntityProperty_FK1", "met_EnumerationType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<EnumerationTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                            "Type_met_EntityProperty_FK1", "met_EnumerationType", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EntityTypeInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", Name="EntityTypeInfo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EntityTypeInfo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EntityTypeInfo object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="entityFullTypeName">Initial value of EntityFullTypeName.</param>
        /// <param name="entityAssemblyName">Initial value of EntityAssemblyName.</param>
        /// <param name="entityTableName">Initial value of EntityTableName.</param>
        /// <param name="historyFullTypeName">Initial value of HistoryFullTypeName.</param>
        /// <param name="historyAssemblyName">Initial value of HistoryAssemblyName.</param>
        /// <param name="historyTableName">Initial value of HistoryTableName.</param>
        public static EntityTypeInfo CreateEntityTypeInfo(int id, string name, string entityFullTypeName, string entityAssemblyName, string entityTableName, string historyFullTypeName, string historyAssemblyName, string historyTableName)
        {
            EntityTypeInfo entityTypeInfo = new EntityTypeInfo();
            entityTypeInfo.ID = id;
            entityTypeInfo.Name = name;
            entityTypeInfo.EntityFullTypeName = entityFullTypeName;
            entityTypeInfo.EntityAssemblyName = entityAssemblyName;
            entityTypeInfo.EntityTableName = entityTableName;
            entityTypeInfo.HistoryFullTypeName = historyFullTypeName;
            entityTypeInfo.HistoryAssemblyName = historyAssemblyName;
            entityTypeInfo.HistoryTableName = historyTableName;
            return entityTypeInfo;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property EntityFullTypeName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityFullTypeName
        {
            get
            {
                return this._EntityFullTypeName;
            }
            set
            {
                this.OnEntityFullTypeNameChanging(value);
                this.ReportPropertyChanging("EntityFullTypeName");
                this._EntityFullTypeName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EntityFullTypeName");
                this.OnEntityFullTypeNameChanged();
            }
        }
        private string _EntityFullTypeName;
        partial void OnEntityFullTypeNameChanging(string value);
        partial void OnEntityFullTypeNameChanged();
        /// <summary>
        /// There are no comments for Property EntityAssemblyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityAssemblyName
        {
            get
            {
                return this._EntityAssemblyName;
            }
            set
            {
                this.OnEntityAssemblyNameChanging(value);
                this.ReportPropertyChanging("EntityAssemblyName");
                this._EntityAssemblyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EntityAssemblyName");
                this.OnEntityAssemblyNameChanged();
            }
        }
        private string _EntityAssemblyName;
        partial void OnEntityAssemblyNameChanging(string value);
        partial void OnEntityAssemblyNameChanged();
        /// <summary>
        /// There are no comments for Property EntityTableName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityTableName
        {
            get
            {
                return this._EntityTableName;
            }
            set
            {
                this.OnEntityTableNameChanging(value);
                this.ReportPropertyChanging("EntityTableName");
                this._EntityTableName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EntityTableName");
                this.OnEntityTableNameChanged();
            }
        }
        private string _EntityTableName;
        partial void OnEntityTableNameChanging(string value);
        partial void OnEntityTableNameChanged();
        /// <summary>
        /// There are no comments for Property HistoryFullTypeName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string HistoryFullTypeName
        {
            get
            {
                return this._HistoryFullTypeName;
            }
            set
            {
                this.OnHistoryFullTypeNameChanging(value);
                this.ReportPropertyChanging("HistoryFullTypeName");
                this._HistoryFullTypeName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("HistoryFullTypeName");
                this.OnHistoryFullTypeNameChanged();
            }
        }
        private string _HistoryFullTypeName;
        partial void OnHistoryFullTypeNameChanging(string value);
        partial void OnHistoryFullTypeNameChanged();
        /// <summary>
        /// There are no comments for Property HistoryAssemblyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string HistoryAssemblyName
        {
            get
            {
                return this._HistoryAssemblyName;
            }
            set
            {
                this.OnHistoryAssemblyNameChanging(value);
                this.ReportPropertyChanging("HistoryAssemblyName");
                this._HistoryAssemblyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("HistoryAssemblyName");
                this.OnHistoryAssemblyNameChanged();
            }
        }
        private string _HistoryAssemblyName;
        partial void OnHistoryAssemblyNameChanging(string value);
        partial void OnHistoryAssemblyNameChanged();
        /// <summary>
        /// There are no comments for Property HistoryTableName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string HistoryTableName
        {
            get
            {
                return this._HistoryTableName;
            }
            set
            {
                this.OnHistoryTableNameChanging(value);
                this.ReportPropertyChanging("HistoryTableName");
                this._HistoryTableName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("HistoryTableName");
                this.OnHistoryTableNameChanged();
            }
        }
        private string _HistoryTableName;
        partial void OnHistoryTableNameChanging(string value);
        partial void OnHistoryTableNameChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Properties in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EntityType_met_EntityProperty_FK1", "met_EntityProperty")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<EntityPropertyInfo> Properties
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                        "met_EntityProperty_FK1", "met_EntityProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                            "met_EntityProperty_FK1", "met_EntityProperty", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ReferencingProperties in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EntityType_met_EntityProperty_FK2", "met_EntityProperty")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<EntityPropertyInfo> ReferencingProperties
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                        "met_EntityProperty_FK2", "met_EntityProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_EntityType_" +
                            "met_EntityProperty_FK2", "met_EntityProperty", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EnumerationItemInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", Name="EnumerationItemInfo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EnumerationItemInfo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EnumerationItemInfo object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="name">Initial value of Name.</param>
        public static EnumerationItemInfo CreateEnumerationItemInfo(int id, byte value, string name)
        {
            EnumerationItemInfo enumerationItemInfo = new EnumerationItemInfo();
            enumerationItemInfo.ID = id;
            enumerationItemInfo.Value = value;
            enumerationItemInfo.Name = name;
            return enumerationItemInfo;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private byte _Value;
        partial void OnValueChanging(byte value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Enumeration in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EnumerationType_met_EnumerationItem_FK1", "met_EnumerationType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public EnumerationTypeInfo Enumeration
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EnumerationTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                        "Type_met_EnumerationItem_FK1", "met_EnumerationType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EnumerationTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                        "Type_met_EnumerationItem_FK1", "met_EnumerationType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Enumeration in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<EnumerationTypeInfo> EnumerationReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EnumerationTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                        "Type_met_EnumerationItem_FK1", "met_EnumerationType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<EnumerationTypeInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                            "Type_met_EnumerationItem_FK1", "met_EnumerationType", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.EnumerationTypeInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", Name="EnumerationTypeInfo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EnumerationTypeInfo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EnumerationTypeInfo object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="fullTypeName">Initial value of FullTypeName.</param>
        /// <param name="assemblyName">Initial value of AssemblyName.</param>
        /// <param name="isFlag">Initial value of IsFlag.</param>
        public static EnumerationTypeInfo CreateEnumerationTypeInfo(int id, string fullTypeName, string assemblyName, bool isFlag)
        {
            EnumerationTypeInfo enumerationTypeInfo = new EnumerationTypeInfo();
            enumerationTypeInfo.ID = id;
            enumerationTypeInfo.FullTypeName = fullTypeName;
            enumerationTypeInfo.AssemblyName = assemblyName;
            enumerationTypeInfo.IsFlag = isFlag;
            return enumerationTypeInfo;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property FullTypeName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FullTypeName
        {
            get
            {
                return this._FullTypeName;
            }
            set
            {
                this.OnFullTypeNameChanging(value);
                this.ReportPropertyChanging("FullTypeName");
                this._FullTypeName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FullTypeName");
                this.OnFullTypeNameChanged();
            }
        }
        private string _FullTypeName;
        partial void OnFullTypeNameChanging(string value);
        partial void OnFullTypeNameChanged();
        /// <summary>
        /// There are no comments for Property AssemblyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AssemblyName
        {
            get
            {
                return this._AssemblyName;
            }
            set
            {
                this.OnAssemblyNameChanging(value);
                this.ReportPropertyChanging("AssemblyName");
                this._AssemblyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AssemblyName");
                this.OnAssemblyNameChanged();
            }
        }
        private string _AssemblyName;
        partial void OnAssemblyNameChanging(string value);
        partial void OnAssemblyNameChanged();
        /// <summary>
        /// There are no comments for Property IsFlag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFlag
        {
            get
            {
                return this._IsFlag;
            }
            set
            {
                this.OnIsFlagChanging(value);
                this.ReportPropertyChanging("IsFlag");
                this._IsFlag = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsFlag");
                this.OnIsFlagChanged();
            }
        }
        private bool _IsFlag;
        partial void OnIsFlagChanging(bool value);
        partial void OnIsFlagChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for ReferencingProperties in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EnumerationType_met_EntityProperty_FK1", "met_EntityProperty")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<EntityPropertyInfo> ReferencingProperties
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                        "Type_met_EntityProperty_FK1", "met_EntityProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<EntityPropertyInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                            "Type_met_EntityProperty_FK1", "met_EntityProperty", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Items in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata", "met_EnumerationType_met_EnumerationItem_FK1", "met_EnumerationItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<EnumerationItemInfo> Items
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<EnumerationItemInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                        "Type_met_EnumerationItem_FK1", "met_EnumerationItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<EnumerationItemInfo>("Wang.Velika.FamilyAccounting.Application.Framework.EntityMetadata.met_Enumeration" +
                            "Type_met_EnumerationItem_FK1", "met_EnumerationItem", value);
                }
            }
        }
    }
}
