ALTER TABLE [ast_EntityHistoryRepresentation] ADD  CONSTRAINT [ast_EntityHistoryRepresentation_PK] PRIMARY KEY CLUSTERED 
(
	[EntityTypeID] ASC,
	[EntityID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO
