CREATE UNIQUE NONCLUSTERED INDEX [ent_ResourceContent_AK1] ON [ent_ResourceContent] 
(
	[LanguageSetID] ASC,
	[ResourceKeyID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO
