CREATE UNIQUE NONCLUSTERED INDEX [met_EntityType_AK2] ON [met_EntityType] 
(
	[EntityFullTypeName] ASC,
	[EntityAssemblyName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO
