ALTER TABLE [rel_ResourceGroup_ResourceKey] ADD  CONSTRAINT [rel_ResourceGroup_ResourceKey_PK] PRIMARY KEY CLUSTERED 
(
	[ResourceGroupID] ASC,
	[ResourceKeyID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO
