ALTER TABLE [rel_PermissionSet_Permission] ADD  CONSTRAINT [rel_PermissionSet_Permission_PK] PRIMARY KEY CLUSTERED 
(
	[PermissionSetID] ASC,
	[PermissionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO
