//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Authorization", "rel_PermissionSet_Permission", "met_Permission", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Authorization.Permission), "met_PermissionSet", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Authorization.PermissionSet))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Authorization", "rel_Role_PermissionSet", "ent_Role", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Authorization.Role), "met_PermissionSet", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Authorization.PermissionSet))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Authorization", "rel_User_Role", "ent_Role", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Authorization.Role), "ent_User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Authorization.User))]

// Original file name:
// Generation date: 2009-9-23 9:56:00
namespace Wang.Velika.FamilyAccounting.Application.Framework.Authorization
{
    
    /// <summary>
    /// There are no comments for AuthorizationContext in the schema.
    /// </summary>
    public partial class AuthorizationContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new AuthorizationContext object using the connection string found in the 'AuthorizationContext' section of the application configuration file.
        /// </summary>
        public AuthorizationContext() : 
                base("name=AuthorizationContext", "AuthorizationContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new AuthorizationContext object.
        /// </summary>
        public AuthorizationContext(string connectionString) : 
                base(connectionString, "AuthorizationContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new AuthorizationContext object.
        /// </summary>
        public AuthorizationContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "AuthorizationContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for RoleSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Role> RoleSet
        {
            get
            {
                if ((this._RoleSet == null))
                {
                    this._RoleSet = base.CreateQuery<Role>("[RoleSet]");
                }
                return this._RoleSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Role> _RoleSet;
        /// <summary>
        /// There are no comments for UserSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> UserSet
        {
            get
            {
                if ((this._UserSet == null))
                {
                    this._UserSet = base.CreateQuery<User>("[UserSet]");
                }
                return this._UserSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _UserSet;
        /// <summary>
        /// There are no comments for PermissionSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Permission> PermissionSet
        {
            get
            {
                if ((this._PermissionSet == null))
                {
                    this._PermissionSet = base.CreateQuery<Permission>("[PermissionSet]");
                }
                return this._PermissionSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Permission> _PermissionSet;
        /// <summary>
        /// There are no comments for PermissionSetSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PermissionSet> PermissionSetSet
        {
            get
            {
                if ((this._PermissionSetSet == null))
                {
                    this._PermissionSetSet = base.CreateQuery<PermissionSet>("[PermissionSetSet]");
                }
                return this._PermissionSetSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PermissionSet> _PermissionSetSet;
        /// <summary>
        /// There are no comments for RoleHistorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<RoleHistory> RoleHistorySet
        {
            get
            {
                if ((this._RoleHistorySet == null))
                {
                    this._RoleHistorySet = base.CreateQuery<RoleHistory>("[RoleHistorySet]");
                }
                return this._RoleHistorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<RoleHistory> _RoleHistorySet;
        /// <summary>
        /// There are no comments for UserHistorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UserHistory> UserHistorySet
        {
            get
            {
                if ((this._UserHistorySet == null))
                {
                    this._UserHistorySet = base.CreateQuery<UserHistory>("[UserHistorySet]");
                }
                return this._UserHistorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UserHistory> _UserHistorySet;
        /// <summary>
        /// There are no comments for RoleSet in the schema.
        /// </summary>
        public void AddToRoleSet(Role role)
        {
            base.AddObject("RoleSet", role);
        }
        /// <summary>
        /// There are no comments for UserSet in the schema.
        /// </summary>
        public void AddToUserSet(User user)
        {
            base.AddObject("UserSet", user);
        }
        /// <summary>
        /// There are no comments for PermissionSet in the schema.
        /// </summary>
        public void AddToPermissionSet(Permission permission)
        {
            base.AddObject("PermissionSet", permission);
        }
        /// <summary>
        /// There are no comments for PermissionSetSet in the schema.
        /// </summary>
        public void AddToPermissionSetSet(PermissionSet permissionSet)
        {
            base.AddObject("PermissionSetSet", permissionSet);
        }
        /// <summary>
        /// There are no comments for RoleHistorySet in the schema.
        /// </summary>
        public void AddToRoleHistorySet(RoleHistory roleHistory)
        {
            base.AddObject("RoleHistorySet", roleHistory);
        }
        /// <summary>
        /// There are no comments for UserHistorySet in the schema.
        /// </summary>
        public void AddToUserHistorySet(UserHistory userHistory)
        {
            base.AddObject("UserHistorySet", userHistory);
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Authorization.Role in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Authorization", Name="Role")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Role : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="isFixed">Initial value of IsFixed.</param>
        public static Role CreateRole(int id, string name, bool isFixed)
        {
            Role role = new Role();
            role.ID = id;
            role.Name = name;
            role.IsFixed = isFixed;
            return role;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IsFixed in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFixed
        {
            get
            {
                return this._IsFixed;
            }
            set
            {
                this.OnIsFixedChanging(value);
                this.ReportPropertyChanging("IsFixed");
                this._IsFixed = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsFixed");
                this.OnIsFixedChanged();
            }
        }
        private bool _IsFixed;
        partial void OnIsFixedChanging(bool value);
        partial void OnIsFixedChanged();
        /// <summary>
        /// There are no comments for PermissionSets in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Authorization", "rel_Role_PermissionSet", "met_PermissionSet")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PermissionSet> PermissionSets
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PermissionSet>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_Role_Permiss" +
                        "ionSet", "met_PermissionSet");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PermissionSet>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_Role_Permiss" +
                            "ionSet", "met_PermissionSet", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Authorization", "rel_User_Role", "ent_User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<User> Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<User>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_User_Role", "ent_User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<User>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_User_Role", "ent_User", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Authorization.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Authorization", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static User CreateUser(int id, string name)
        {
            User user = new User();
            user.ID = id;
            user.Name = name;
            return user;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Authorization", "rel_User_Role", "ent_Role")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Role> Roles
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Role>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_User_Role", "ent_Role");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Role>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_User_Role", "ent_Role", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Authorization.Permission in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Authorization", Name="Permission")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Permission : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Permission object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Permission CreatePermission(int id, string name)
        {
            Permission permission = new Permission();
            permission.ID = id;
            permission.Name = name;
            return permission;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for BelongToPermissionSets in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Authorization", "rel_PermissionSet_Permission", "met_PermissionSet")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<PermissionSet> BelongToPermissionSets
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PermissionSet>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_PermissionSe" +
                        "t_Permission", "met_PermissionSet");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PermissionSet>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_PermissionSe" +
                            "t_Permission", "met_PermissionSet", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Authorization.PermissionSet in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Authorization", Name="PermissionSet")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PermissionSet : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PermissionSet object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static PermissionSet CreatePermissionSet(int id, string name)
        {
            PermissionSet permissionSet = new PermissionSet();
            permissionSet.ID = id;
            permissionSet.Name = name;
            return permissionSet;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Permissions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Authorization", "rel_PermissionSet_Permission", "met_Permission")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Permission> Permissions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Permission>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_PermissionSe" +
                        "t_Permission", "met_Permission");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Permission>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_PermissionSe" +
                            "t_Permission", "met_Permission", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BelongToRoles in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Authorization", "rel_Role_PermissionSet", "ent_Role")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<Role> BelongToRoles
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Role>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_Role_Permiss" +
                        "ionSet", "ent_Role");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Role>("Wang.Velika.FamilyAccounting.Application.Framework.Authorization.rel_Role_Permiss" +
                            "ionSet", "ent_Role", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Authorization.RoleHistory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Authorization", Name="RoleHistory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class RoleHistory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new RoleHistory object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="roleID">Initial value of RoleID.</param>
        public static RoleHistory CreateRoleHistory(int id, int roleID)
        {
            RoleHistory roleHistory = new RoleHistory();
            roleHistory.ID = id;
            roleHistory.RoleID = roleID;
            return roleHistory;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property RoleID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID
        {
            get
            {
                return this._RoleID;
            }
            set
            {
                this.OnRoleIDChanging(value);
                this.ReportPropertyChanging("RoleID");
                this._RoleID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RoleID");
                this.OnRoleIDChanged();
            }
        }
        private int _RoleID;
        partial void OnRoleIDChanging(int value);
        partial void OnRoleIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IsFixed in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> IsFixed
        {
            get
            {
                return this._IsFixed;
            }
            set
            {
                this.OnIsFixedChanging(value);
                this.ReportPropertyChanging("IsFixed");
                this._IsFixed = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsFixed");
                this.OnIsFixedChanged();
            }
        }
        private global::System.Nullable<bool> _IsFixed;
        partial void OnIsFixedChanging(global::System.Nullable<bool> value);
        partial void OnIsFixedChanged();
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Authorization.UserHistory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Authorization", Name="UserHistory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UserHistory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new UserHistory object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="userID">Initial value of UserID.</param>
        public static UserHistory CreateUserHistory(int id, int userID)
        {
            UserHistory userHistory = new UserHistory();
            userHistory.ID = id;
            userHistory.UserID = userID;
            return userHistory;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property UserID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this.OnUserIDChanging(value);
                this.ReportPropertyChanging("UserID");
                this._UserID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserID");
                this.OnUserIDChanged();
            }
        }
        private int _UserID;
        partial void OnUserIDChanging(int value);
        partial void OnUserIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
}
