//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "ent_Table1_ent_Table4_FK1", "ent_Table1", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table1), "ent_Table4", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table4))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "ent_Table2_ent_Table4_FK1", "ent_Table2", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table2), "ent_Table4", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table4))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "met_Table3_ent_Table4_FK1", "met_Table3", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table3), "ent_Table4", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table4))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "rel_Table4_Table5_1", "ent_Table4", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table4), "ent_Table5", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table5))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "rel_Table4_Table5_2", "ent_Table4", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table4), "ent_Table5", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table5))]

// Original file name:
// Generation date: 2009-9-29 9:40:49
namespace Wang.Velika.FamilyAccounting.Application.Framework.Test.History
{
    
    /// <summary>
    /// There are no comments for TestHistoryContext in the schema.
    /// </summary>
    public partial class TestHistoryContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new TestHistoryContext object using the connection string found in the 'TestHistoryContext' section of the application configuration file.
        /// </summary>
        public TestHistoryContext() : 
                base("name=TestHistoryContext", "TestHistoryContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TestHistoryContext object.
        /// </summary>
        public TestHistoryContext(string connectionString) : 
                base(connectionString, "TestHistoryContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TestHistoryContext object.
        /// </summary>
        public TestHistoryContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TestHistoryContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Table1Set in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Table1> Table1Set
        {
            get
            {
                if ((this._Table1Set == null))
                {
                    this._Table1Set = base.CreateQuery<Table1>("[Table1Set]");
                }
                return this._Table1Set;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Table1> _Table1Set;
        /// <summary>
        /// There are no comments for Table2Set in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Table2> Table2Set
        {
            get
            {
                if ((this._Table2Set == null))
                {
                    this._Table2Set = base.CreateQuery<Table2>("[Table2Set]");
                }
                return this._Table2Set;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Table2> _Table2Set;
        /// <summary>
        /// There are no comments for Table4Set in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Table4> Table4Set
        {
            get
            {
                if ((this._Table4Set == null))
                {
                    this._Table4Set = base.CreateQuery<Table4>("[Table4Set]");
                }
                return this._Table4Set;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Table4> _Table4Set;
        /// <summary>
        /// There are no comments for Table5Set in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Table5> Table5Set
        {
            get
            {
                if ((this._Table5Set == null))
                {
                    this._Table5Set = base.CreateQuery<Table5>("[Table5Set]");
                }
                return this._Table5Set;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Table5> _Table5Set;
        /// <summary>
        /// There are no comments for Table3Set in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Table3> Table3Set
        {
            get
            {
                if ((this._Table3Set == null))
                {
                    this._Table3Set = base.CreateQuery<Table3>("[Table3Set]");
                }
                return this._Table3Set;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Table3> _Table3Set;
        /// <summary>
        /// There are no comments for Table1HistorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Table1History> Table1HistorySet
        {
            get
            {
                if ((this._Table1HistorySet == null))
                {
                    this._Table1HistorySet = base.CreateQuery<Table1History>("[Table1HistorySet]");
                }
                return this._Table1HistorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Table1History> _Table1HistorySet;
        /// <summary>
        /// There are no comments for Table2HistorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Table2History> Table2HistorySet
        {
            get
            {
                if ((this._Table2HistorySet == null))
                {
                    this._Table2HistorySet = base.CreateQuery<Table2History>("[Table2HistorySet]");
                }
                return this._Table2HistorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Table2History> _Table2HistorySet;
        /// <summary>
        /// There are no comments for Table4HistorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Table4History> Table4HistorySet
        {
            get
            {
                if ((this._Table4HistorySet == null))
                {
                    this._Table4HistorySet = base.CreateQuery<Table4History>("[Table4HistorySet]");
                }
                return this._Table4HistorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Table4History> _Table4HistorySet;
        /// <summary>
        /// There are no comments for Table5HistorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Table5History> Table5HistorySet
        {
            get
            {
                if ((this._Table5HistorySet == null))
                {
                    this._Table5HistorySet = base.CreateQuery<Table5History>("[Table5HistorySet]");
                }
                return this._Table5HistorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Table5History> _Table5HistorySet;
        /// <summary>
        /// There are no comments for Table1Set in the schema.
        /// </summary>
        public void AddToTable1Set(Table1 table1)
        {
            base.AddObject("Table1Set", table1);
        }
        /// <summary>
        /// There are no comments for Table2Set in the schema.
        /// </summary>
        public void AddToTable2Set(Table2 table2)
        {
            base.AddObject("Table2Set", table2);
        }
        /// <summary>
        /// There are no comments for Table4Set in the schema.
        /// </summary>
        public void AddToTable4Set(Table4 table4)
        {
            base.AddObject("Table4Set", table4);
        }
        /// <summary>
        /// There are no comments for Table5Set in the schema.
        /// </summary>
        public void AddToTable5Set(Table5 table5)
        {
            base.AddObject("Table5Set", table5);
        }
        /// <summary>
        /// There are no comments for Table3Set in the schema.
        /// </summary>
        public void AddToTable3Set(Table3 table3)
        {
            base.AddObject("Table3Set", table3);
        }
        /// <summary>
        /// There are no comments for Table1HistorySet in the schema.
        /// </summary>
        public void AddToTable1HistorySet(Table1History table1History)
        {
            base.AddObject("Table1HistorySet", table1History);
        }
        /// <summary>
        /// There are no comments for Table2HistorySet in the schema.
        /// </summary>
        public void AddToTable2HistorySet(Table2History table2History)
        {
            base.AddObject("Table2HistorySet", table2History);
        }
        /// <summary>
        /// There are no comments for Table4HistorySet in the schema.
        /// </summary>
        public void AddToTable4HistorySet(Table4History table4History)
        {
            base.AddObject("Table4HistorySet", table4History);
        }
        /// <summary>
        /// There are no comments for Table5HistorySet in the schema.
        /// </summary>
        public void AddToTable5HistorySet(Table5History table5History)
        {
            base.AddObject("Table5HistorySet", table5History);
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table1 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Test.History", Name="Table1")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Table1 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Table1 object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="propertyInt">Initial value of PropertyInt.</param>
        public static Table1 CreateTable1(int id, int propertyInt)
        {
            Table1 table1 = new Table1();
            table1.ID = id;
            table1.PropertyInt = propertyInt;
            return table1;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PropertyInt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyInt
        {
            get
            {
                return this._PropertyInt;
            }
            set
            {
                this.OnPropertyIntChanging(value);
                this.ReportPropertyChanging("PropertyInt");
                this._PropertyInt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PropertyInt");
                this.OnPropertyIntChanged();
            }
        }
        private int _PropertyInt;
        partial void OnPropertyIntChanging(int value);
        partial void OnPropertyIntChanged();
        /// <summary>
        /// There are no comments for Property PropertyString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyString
        {
            get
            {
                return this._PropertyString;
            }
            set
            {
                this.OnPropertyStringChanging(value);
                this.ReportPropertyChanging("PropertyString");
                this._PropertyString = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PropertyString");
                this.OnPropertyStringChanged();
            }
        }
        private string _PropertyString;
        partial void OnPropertyStringChanging(string value);
        partial void OnPropertyStringChanged();
        /// <summary>
        /// There are no comments for Property PropertyDatetime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> PropertyDatetime
        {
            get
            {
                return this._PropertyDatetime;
            }
            set
            {
                this.OnPropertyDatetimeChanging(value);
                this.ReportPropertyChanging("PropertyDatetime");
                this._PropertyDatetime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PropertyDatetime");
                this.OnPropertyDatetimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _PropertyDatetime;
        partial void OnPropertyDatetimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPropertyDatetimeChanged();
        /// <summary>
        /// There are no comments for DualTable4sRaw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "ent_Table1_ent_Table4_FK1", "ent_Table4")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<Table4> DualTable4sRaw
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Table4>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table1_ent_Ta" +
                        "ble4_FK1", "ent_Table4");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Table4>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table1_ent_Ta" +
                            "ble4_FK1", "ent_Table4", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table2 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Test.History", Name="Table2")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Table2 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Table2 object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Table2 CreateTable2(int id)
        {
            Table2 table2 = new Table2();
            table2.ID = id;
            return table2;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PropertyString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyString
        {
            get
            {
                return this._PropertyString;
            }
            set
            {
                this.OnPropertyStringChanging(value);
                this.ReportPropertyChanging("PropertyString");
                this._PropertyString = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PropertyString");
                this.OnPropertyStringChanged();
            }
        }
        private string _PropertyString;
        partial void OnPropertyStringChanging(string value);
        partial void OnPropertyStringChanged();
        /// <summary>
        /// There are no comments for ent_Table4 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "ent_Table2_ent_Table4_FK1", "ent_Table4")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<Table4> ent_Table4
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Table4>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table2_ent_Ta" +
                        "ble4_FK1", "ent_Table4");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Table4>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table2_ent_Ta" +
                            "ble4_FK1", "ent_Table4", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table4 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Test.History", Name="Table4")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Table4 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Table4 object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Table4 CreateTable4(int id)
        {
            Table4 table4 = new Table4();
            table4.ID = id;
            return table4;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PropertyString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyString
        {
            get
            {
                return this._PropertyString;
            }
            set
            {
                this.OnPropertyStringChanging(value);
                this.ReportPropertyChanging("PropertyString");
                this._PropertyString = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PropertyString");
                this.OnPropertyStringChanged();
            }
        }
        private string _PropertyString;
        partial void OnPropertyStringChanging(string value);
        partial void OnPropertyStringChanged();
        /// <summary>
        /// There are no comments for DualTable1Raw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "ent_Table1_ent_Table4_FK1", "ent_Table1")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private Table1 DualTable1Raw
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Table1>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table1_ent_Ta" +
                        "ble4_FK1", "ent_Table1").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Table1>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table1_ent_Ta" +
                        "ble4_FK1", "ent_Table1").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for DualTable1Raw in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityReference<Table1> DualTable1RawReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Table1>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table1_ent_Ta" +
                        "ble4_FK1", "ent_Table1");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Table1>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table1_ent_Ta" +
                            "ble4_FK1", "ent_Table1", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for MonoTable2Raw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "ent_Table2_ent_Table4_FK1", "ent_Table2")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private Table2 MonoTable2Raw
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Table2>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table2_ent_Ta" +
                        "ble4_FK1", "ent_Table2").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Table2>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table2_ent_Ta" +
                        "ble4_FK1", "ent_Table2").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for MonoTable2Raw in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityReference<Table2> MonoTable2RawReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Table2>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table2_ent_Ta" +
                        "ble4_FK1", "ent_Table2");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Table2>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.ent_Table2_ent_Ta" +
                            "ble4_FK1", "ent_Table2", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for MetaTable3Raw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "met_Table3_ent_Table4_FK1", "met_Table3")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private Table3 MetaTable3Raw
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Table3>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.met_Table3_ent_Ta" +
                        "ble4_FK1", "met_Table3").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Table3>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.met_Table3_ent_Ta" +
                        "ble4_FK1", "met_Table3").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for MetaTable3Raw in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityReference<Table3> MetaTable3RawReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Table3>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.met_Table3_ent_Ta" +
                        "ble4_FK1", "met_Table3");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Table3>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.met_Table3_ent_Ta" +
                            "ble4_FK1", "met_Table3", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for DualTable5sRaw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "rel_Table4_Table5_1", "ent_Table5")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<Table5> DualTable5sRaw
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Table5>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.rel_Table4_Table5" +
                        "_1", "ent_Table5");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Table5>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.rel_Table4_Table5" +
                            "_1", "ent_Table5", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for MonoTable5sRaw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "rel_Table4_Table5_2", "ent_Table5")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<Table5> MonoTable5sRaw
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Table5>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.rel_Table4_Table5" +
                        "_2", "ent_Table5");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Table5>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.rel_Table4_Table5" +
                            "_2", "ent_Table5", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table5 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Test.History", Name="Table5")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Table5 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Table5 object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Table5 CreateTable5(int id)
        {
            Table5 table5 = new Table5();
            table5.ID = id;
            return table5;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PropertyInt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> PropertyInt
        {
            get
            {
                return this._PropertyInt;
            }
            set
            {
                this.OnPropertyIntChanging(value);
                this.ReportPropertyChanging("PropertyInt");
                this._PropertyInt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PropertyInt");
                this.OnPropertyIntChanged();
            }
        }
        private global::System.Nullable<int> _PropertyInt;
        partial void OnPropertyIntChanging(global::System.Nullable<int> value);
        partial void OnPropertyIntChanged();
        /// <summary>
        /// There are no comments for DualTable4sRaw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "rel_Table4_Table5_1", "ent_Table4")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<Table4> DualTable4sRaw
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Table4>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.rel_Table4_Table5" +
                        "_1", "ent_Table4");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Table4>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.rel_Table4_Table5" +
                            "_1", "ent_Table4", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ent_Table41 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "rel_Table4_Table5_2", "ent_Table4")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<Table4> ent_Table41
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Table4>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.rel_Table4_Table5" +
                        "_2", "ent_Table4");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Table4>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.rel_Table4_Table5" +
                            "_2", "ent_Table4", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table3 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Test.History", Name="Table3")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Table3 : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Table3 object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="propertyString">Initial value of PropertyString.</param>
        public static Table3 CreateTable3(int id, string propertyString)
        {
            Table3 table3 = new Table3();
            table3.ID = id;
            table3.PropertyString = propertyString;
            return table3;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PropertyString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyString
        {
            get
            {
                return this._PropertyString;
            }
            set
            {
                this.OnPropertyStringChanging(value);
                this.ReportPropertyChanging("PropertyString");
                this._PropertyString = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PropertyString");
                this.OnPropertyStringChanged();
            }
        }
        private string _PropertyString;
        partial void OnPropertyStringChanging(string value);
        partial void OnPropertyStringChanged();
        /// <summary>
        /// There are no comments for ent_Table4 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Test.History", "met_Table3_ent_Table4_FK1", "ent_Table4")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<Table4> ent_Table4
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Table4>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.met_Table3_ent_Ta" +
                        "ble4_FK1", "ent_Table4");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Table4>("Wang.Velika.FamilyAccounting.Application.Framework.Test.History.met_Table3_ent_Ta" +
                            "ble4_FK1", "ent_Table4", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table1History in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Test.History", Name="Table1History")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Table1History : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Table1History object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="table1ID">Initial value of Table1ID.</param>
        public static Table1History CreateTable1History(int id, int table1ID)
        {
            Table1History table1History = new Table1History();
            table1History.ID = id;
            table1History.Table1ID = table1ID;
            return table1History;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Table1ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Table1ID
        {
            get
            {
                return this._Table1ID;
            }
            set
            {
                this.OnTable1IDChanging(value);
                this.ReportPropertyChanging("Table1ID");
                this._Table1ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Table1ID");
                this.OnTable1IDChanged();
            }
        }
        private int _Table1ID;
        partial void OnTable1IDChanging(int value);
        partial void OnTable1IDChanged();
        /// <summary>
        /// There are no comments for Property PropertyInt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> PropertyInt
        {
            get
            {
                return this._PropertyInt;
            }
            set
            {
                this.OnPropertyIntChanging(value);
                this.ReportPropertyChanging("PropertyInt");
                this._PropertyInt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PropertyInt");
                this.OnPropertyIntChanged();
            }
        }
        private global::System.Nullable<int> _PropertyInt;
        partial void OnPropertyIntChanging(global::System.Nullable<int> value);
        partial void OnPropertyIntChanged();
        /// <summary>
        /// There are no comments for Property PropertyString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyString
        {
            get
            {
                return this._PropertyString;
            }
            set
            {
                this.OnPropertyStringChanging(value);
                this.ReportPropertyChanging("PropertyString");
                this._PropertyString = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PropertyString");
                this.OnPropertyStringChanged();
            }
        }
        private string _PropertyString;
        partial void OnPropertyStringChanging(string value);
        partial void OnPropertyStringChanged();
        /// <summary>
        /// There are no comments for Property PropertyDatetime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> PropertyDatetime
        {
            get
            {
                return this._PropertyDatetime;
            }
            set
            {
                this.OnPropertyDatetimeChanging(value);
                this.ReportPropertyChanging("PropertyDatetime");
                this._PropertyDatetime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PropertyDatetime");
                this.OnPropertyDatetimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _PropertyDatetime;
        partial void OnPropertyDatetimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPropertyDatetimeChanged();
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table2History in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Test.History", Name="Table2History")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Table2History : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Table2History object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="table2ID">Initial value of Table2ID.</param>
        public static Table2History CreateTable2History(int id, int table2ID)
        {
            Table2History table2History = new Table2History();
            table2History.ID = id;
            table2History.Table2ID = table2ID;
            return table2History;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Table2ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Table2ID
        {
            get
            {
                return this._Table2ID;
            }
            set
            {
                this.OnTable2IDChanging(value);
                this.ReportPropertyChanging("Table2ID");
                this._Table2ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Table2ID");
                this.OnTable2IDChanged();
            }
        }
        private int _Table2ID;
        partial void OnTable2IDChanging(int value);
        partial void OnTable2IDChanged();
        /// <summary>
        /// There are no comments for Property PropertyString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyString
        {
            get
            {
                return this._PropertyString;
            }
            set
            {
                this.OnPropertyStringChanging(value);
                this.ReportPropertyChanging("PropertyString");
                this._PropertyString = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PropertyString");
                this.OnPropertyStringChanged();
            }
        }
        private string _PropertyString;
        partial void OnPropertyStringChanging(string value);
        partial void OnPropertyStringChanged();
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table4History in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Test.History", Name="Table4History")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Table4History : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Table4History object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="table4ID">Initial value of Table4ID.</param>
        public static Table4History CreateTable4History(int id, int table4ID)
        {
            Table4History table4History = new Table4History();
            table4History.ID = id;
            table4History.Table4ID = table4ID;
            return table4History;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Table4ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Table4ID
        {
            get
            {
                return this._Table4ID;
            }
            set
            {
                this.OnTable4IDChanging(value);
                this.ReportPropertyChanging("Table4ID");
                this._Table4ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Table4ID");
                this.OnTable4IDChanged();
            }
        }
        private int _Table4ID;
        partial void OnTable4IDChanging(int value);
        partial void OnTable4IDChanged();
        /// <summary>
        /// There are no comments for Property Table1ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Table1ID
        {
            get
            {
                return this._Table1ID;
            }
            set
            {
                this.OnTable1IDChanging(value);
                this.ReportPropertyChanging("Table1ID");
                this._Table1ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Table1ID");
                this.OnTable1IDChanged();
            }
        }
        private global::System.Nullable<int> _Table1ID;
        partial void OnTable1IDChanging(global::System.Nullable<int> value);
        partial void OnTable1IDChanged();
        /// <summary>
        /// There are no comments for Property Table2ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Table2ID
        {
            get
            {
                return this._Table2ID;
            }
            set
            {
                this.OnTable2IDChanging(value);
                this.ReportPropertyChanging("Table2ID");
                this._Table2ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Table2ID");
                this.OnTable2IDChanged();
            }
        }
        private global::System.Nullable<int> _Table2ID;
        partial void OnTable2IDChanging(global::System.Nullable<int> value);
        partial void OnTable2IDChanged();
        /// <summary>
        /// There are no comments for Property PropertyString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyString
        {
            get
            {
                return this._PropertyString;
            }
            set
            {
                this.OnPropertyStringChanging(value);
                this.ReportPropertyChanging("PropertyString");
                this._PropertyString = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PropertyString");
                this.OnPropertyStringChanged();
            }
        }
        private string _PropertyString;
        partial void OnPropertyStringChanging(string value);
        partial void OnPropertyStringChanged();
        /// <summary>
        /// There are no comments for Property Table3ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Table3ID
        {
            get
            {
                return this._Table3ID;
            }
            set
            {
                this.OnTable3IDChanging(value);
                this.ReportPropertyChanging("Table3ID");
                this._Table3ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Table3ID");
                this.OnTable3IDChanged();
            }
        }
        private global::System.Nullable<int> _Table3ID;
        partial void OnTable3IDChanging(global::System.Nullable<int> value);
        partial void OnTable3IDChanged();
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Test.History.Table5History in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Test.History", Name="Table5History")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Table5History : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Table5History object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="table5ID">Initial value of Table5ID.</param>
        public static Table5History CreateTable5History(int id, int table5ID)
        {
            Table5History table5History = new Table5History();
            table5History.ID = id;
            table5History.Table5ID = table5ID;
            return table5History;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Table5ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Table5ID
        {
            get
            {
                return this._Table5ID;
            }
            set
            {
                this.OnTable5IDChanging(value);
                this.ReportPropertyChanging("Table5ID");
                this._Table5ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Table5ID");
                this.OnTable5IDChanged();
            }
        }
        private int _Table5ID;
        partial void OnTable5IDChanging(int value);
        partial void OnTable5IDChanged();
        /// <summary>
        /// There are no comments for Property PropertyInt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> PropertyInt
        {
            get
            {
                return this._PropertyInt;
            }
            set
            {
                this.OnPropertyIntChanging(value);
                this.ReportPropertyChanging("PropertyInt");
                this._PropertyInt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PropertyInt");
                this.OnPropertyIntChanged();
            }
        }
        private global::System.Nullable<int> _PropertyInt;
        partial void OnPropertyIntChanging(global::System.Nullable<int> value);
        partial void OnPropertyIntChanged();
    }
}
