ALTER TABLE [rel_Table4_Table5_1] ADD  CONSTRAINT [rel_Table4_Table5_PK] PRIMARY KEY CLUSTERED 
(
	[Table4ID] ASC,
	[Table5ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO
