//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Globalization", "ent_LanguageSet_ent_ResourceContent_FK1", "ent_LanguageSet", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Globalization.LanguageSet), "ent_ResourceContent", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ResourceContent))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Globalization", "met_ResourceKey_ent_ResourceContent_FK1", "met_ResourceKey", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ResourceKey), "ent_ResourceContent", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ResourceContent))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Globalization", "rel_ResourceGroup_ResourceKey", "met_ResourceGroup", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ResourceGroup), "met_ResourceKey", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ResourceKey))]

// Original file name:
// Generation date: 2009-9-24 15:51:21
namespace Wang.Velika.FamilyAccounting.Application.Framework.Globalization
{
    
    /// <summary>
    /// There are no comments for GlobalizationContext in the schema.
    /// </summary>
    public partial class GlobalizationContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new GlobalizationContext object using the connection string found in the 'GlobalizationContext' section of the application configuration file.
        /// </summary>
        public GlobalizationContext() : 
                base("name=GlobalizationContext", "GlobalizationContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GlobalizationContext object.
        /// </summary>
        public GlobalizationContext(string connectionString) : 
                base(connectionString, "GlobalizationContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GlobalizationContext object.
        /// </summary>
        public GlobalizationContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "GlobalizationContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for LanguageSetSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LanguageSet> LanguageSetSet
        {
            get
            {
                if ((this._LanguageSetSet == null))
                {
                    this._LanguageSetSet = base.CreateQuery<LanguageSet>("[LanguageSetSet]");
                }
                return this._LanguageSetSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LanguageSet> _LanguageSetSet;
        /// <summary>
        /// There are no comments for ResourceContentSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ResourceContent> ResourceContentSet
        {
            get
            {
                if ((this._ResourceContentSet == null))
                {
                    this._ResourceContentSet = base.CreateQuery<ResourceContent>("[ResourceContentSet]");
                }
                return this._ResourceContentSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ResourceContent> _ResourceContentSet;
        /// <summary>
        /// There are no comments for ResourceGroupSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ResourceGroup> ResourceGroupSet
        {
            get
            {
                if ((this._ResourceGroupSet == null))
                {
                    this._ResourceGroupSet = base.CreateQuery<ResourceGroup>("[ResourceGroupSet]");
                }
                return this._ResourceGroupSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ResourceGroup> _ResourceGroupSet;
        /// <summary>
        /// There are no comments for ResourceKeySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ResourceKey> ResourceKeySet
        {
            get
            {
                if ((this._ResourceKeySet == null))
                {
                    this._ResourceKeySet = base.CreateQuery<ResourceKey>("[ResourceKeySet]");
                }
                return this._ResourceKeySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ResourceKey> _ResourceKeySet;
        /// <summary>
        /// There are no comments for LanguageSetHistorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LanguageSetHistory> LanguageSetHistorySet
        {
            get
            {
                if ((this._LanguageSetHistorySet == null))
                {
                    this._LanguageSetHistorySet = base.CreateQuery<LanguageSetHistory>("[LanguageSetHistorySet]");
                }
                return this._LanguageSetHistorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LanguageSetHistory> _LanguageSetHistorySet;
        /// <summary>
        /// There are no comments for ResourceContentHistorySet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ResourceContentHistory> ResourceContentHistorySet
        {
            get
            {
                if ((this._ResourceContentHistorySet == null))
                {
                    this._ResourceContentHistorySet = base.CreateQuery<ResourceContentHistory>("[ResourceContentHistorySet]");
                }
                return this._ResourceContentHistorySet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ResourceContentHistory> _ResourceContentHistorySet;
        /// <summary>
        /// There are no comments for LanguageSetSet in the schema.
        /// </summary>
        public void AddToLanguageSetSet(LanguageSet languageSet)
        {
            base.AddObject("LanguageSetSet", languageSet);
        }
        /// <summary>
        /// There are no comments for ResourceContentSet in the schema.
        /// </summary>
        public void AddToResourceContentSet(ResourceContent resourceContent)
        {
            base.AddObject("ResourceContentSet", resourceContent);
        }
        /// <summary>
        /// There are no comments for ResourceGroupSet in the schema.
        /// </summary>
        public void AddToResourceGroupSet(ResourceGroup resourceGroup)
        {
            base.AddObject("ResourceGroupSet", resourceGroup);
        }
        /// <summary>
        /// There are no comments for ResourceKeySet in the schema.
        /// </summary>
        public void AddToResourceKeySet(ResourceKey resourceKey)
        {
            base.AddObject("ResourceKeySet", resourceKey);
        }
        /// <summary>
        /// There are no comments for LanguageSetHistorySet in the schema.
        /// </summary>
        public void AddToLanguageSetHistorySet(LanguageSetHistory languageSetHistory)
        {
            base.AddObject("LanguageSetHistorySet", languageSetHistory);
        }
        /// <summary>
        /// There are no comments for ResourceContentHistorySet in the schema.
        /// </summary>
        public void AddToResourceContentHistorySet(ResourceContentHistory resourceContentHistory)
        {
            base.AddObject("ResourceContentHistorySet", resourceContentHistory);
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Globalization.LanguageSet in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Globalization", Name="LanguageSet")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LanguageSet : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LanguageSet object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static LanguageSet CreateLanguageSet(int id, string name)
        {
            LanguageSet languageSet = new LanguageSet();
            languageSet.ID = id;
            languageSet.Name = name;
            return languageSet;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CultureName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CultureName
        {
            get
            {
                return this._CultureName;
            }
            set
            {
                this.OnCultureNameChanging(value);
                this.ReportPropertyChanging("CultureName");
                this._CultureName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CultureName");
                this.OnCultureNameChanged();
            }
        }
        private string _CultureName;
        partial void OnCultureNameChanging(string value);
        partial void OnCultureNameChanged();
        /// <summary>
        /// There are no comments for Contents in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Globalization", "ent_LanguageSet_ent_ResourceContent_FK1", "ent_ResourceContent")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ResourceContent> Contents
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ResourceContent>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ent_LanguageSet_" +
                        "ent_ResourceContent_FK1", "ent_ResourceContent");
            }
            private set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ResourceContent>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ent_LanguageSet_" +
                            "ent_ResourceContent_FK1", "ent_ResourceContent", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ResourceContent in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Globalization", Name="ResourceContent")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ResourceContent : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ResourceContent object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="content">Initial value of Content.</param>
        public static ResourceContent CreateResourceContent(int id, string content)
        {
            ResourceContent resourceContent = new ResourceContent();
            resourceContent.ID = id;
            resourceContent.Content = content;
            return resourceContent;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Language in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Globalization", "ent_LanguageSet_ent_ResourceContent_FK1", "ent_LanguageSet")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public LanguageSet Language
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LanguageSet>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ent_LanguageSet_" +
                        "ent_ResourceContent_FK1", "ent_LanguageSet").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LanguageSet>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ent_LanguageSet_" +
                        "ent_ResourceContent_FK1", "ent_LanguageSet").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Language in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<LanguageSet> LanguageReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LanguageSet>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ent_LanguageSet_" +
                        "ent_ResourceContent_FK1", "ent_LanguageSet");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<LanguageSet>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ent_LanguageSet_" +
                            "ent_ResourceContent_FK1", "ent_LanguageSet", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Key in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Globalization", "met_ResourceKey_ent_ResourceContent_FK1", "met_ResourceKey")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ResourceKey Key
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ResourceKey>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.met_ResourceKey_" +
                        "ent_ResourceContent_FK1", "met_ResourceKey").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ResourceKey>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.met_ResourceKey_" +
                        "ent_ResourceContent_FK1", "met_ResourceKey").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Key in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ResourceKey> KeyReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ResourceKey>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.met_ResourceKey_" +
                        "ent_ResourceContent_FK1", "met_ResourceKey");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ResourceKey>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.met_ResourceKey_" +
                            "ent_ResourceContent_FK1", "met_ResourceKey", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ResourceGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Globalization", Name="ResourceGroup")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ResourceGroup : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ResourceGroup object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static ResourceGroup CreateResourceGroup(int id, string name)
        {
            ResourceGroup resourceGroup = new ResourceGroup();
            resourceGroup.ID = id;
            resourceGroup.Name = name;
            return resourceGroup;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Keys in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Globalization", "rel_ResourceGroup_ResourceKey", "met_ResourceKey")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ResourceKey> Keys
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ResourceKey>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.rel_ResourceGrou" +
                        "p_ResourceKey", "met_ResourceKey");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ResourceKey>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.rel_ResourceGrou" +
                            "p_ResourceKey", "met_ResourceKey", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ResourceKey in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Globalization", Name="ResourceKey")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ResourceKey : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ResourceKey object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static ResourceKey CreateResourceKey(int id, string name)
        {
            ResourceKey resourceKey = new ResourceKey();
            resourceKey.ID = id;
            resourceKey.Name = name;
            return resourceKey;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Contents in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Globalization", "met_ResourceKey_ent_ResourceContent_FK1", "ent_ResourceContent")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        private global::System.Data.Objects.DataClasses.EntityCollection<ResourceContent> Contents
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ResourceContent>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.met_ResourceKey_" +
                        "ent_ResourceContent_FK1", "ent_ResourceContent");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ResourceContent>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.met_ResourceKey_" +
                            "ent_ResourceContent_FK1", "ent_ResourceContent", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BelongToGroups in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Wang.Velika.FamilyAccounting.Application.Framework.Globalization", "rel_ResourceGroup_ResourceKey", "met_ResourceGroup")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ResourceGroup> BelongToGroups
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ResourceGroup>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.rel_ResourceGrou" +
                        "p_ResourceKey", "met_ResourceGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ResourceGroup>("Wang.Velika.FamilyAccounting.Application.Framework.Globalization.rel_ResourceGrou" +
                            "p_ResourceKey", "met_ResourceGroup", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Globalization.LanguageSetHistory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Globalization", Name="LanguageSetHistory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LanguageSetHistory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LanguageSetHistory object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="languageSetID">Initial value of LanguageSetID.</param>
        public static LanguageSetHistory CreateLanguageSetHistory(int id, int languageSetID)
        {
            LanguageSetHistory languageSetHistory = new LanguageSetHistory();
            languageSetHistory.ID = id;
            languageSetHistory.LanguageSetID = languageSetID;
            return languageSetHistory;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property LanguageSetID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int LanguageSetID
        {
            get
            {
                return this._LanguageSetID;
            }
            set
            {
                this.OnLanguageSetIDChanging(value);
                this.ReportPropertyChanging("LanguageSetID");
                this._LanguageSetID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LanguageSetID");
                this.OnLanguageSetIDChanged();
            }
        }
        private int _LanguageSetID;
        partial void OnLanguageSetIDChanging(int value);
        partial void OnLanguageSetIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CultureName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CultureName
        {
            get
            {
                return this._CultureName;
            }
            set
            {
                this.OnCultureNameChanging(value);
                this.ReportPropertyChanging("CultureName");
                this._CultureName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CultureName");
                this.OnCultureNameChanged();
            }
        }
        private string _CultureName;
        partial void OnCultureNameChanging(string value);
        partial void OnCultureNameChanged();
    }
    /// <summary>
    /// There are no comments for Wang.Velika.FamilyAccounting.Application.Framework.Globalization.ResourceContentHistory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Wang.Velika.FamilyAccounting.Application.Framework.Globalization", Name="ResourceContentHistory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ResourceContentHistory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ResourceContentHistory object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="resourceContentID">Initial value of ResourceContentID.</param>
        public static ResourceContentHistory CreateResourceContentHistory(int id, int resourceContentID)
        {
            ResourceContentHistory resourceContentHistory = new ResourceContentHistory();
            resourceContentHistory.ID = id;
            resourceContentHistory.ResourceContentID = resourceContentID;
            return resourceContentHistory;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property ResourceContentID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ResourceContentID
        {
            get
            {
                return this._ResourceContentID;
            }
            set
            {
                this.OnResourceContentIDChanging(value);
                this.ReportPropertyChanging("ResourceContentID");
                this._ResourceContentID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ResourceContentID");
                this.OnResourceContentIDChanged();
            }
        }
        private int _ResourceContentID;
        partial void OnResourceContentIDChanging(int value);
        partial void OnResourceContentIDChanged();
        /// <summary>
        /// There are no comments for Property LanguageSetID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> LanguageSetID
        {
            get
            {
                return this._LanguageSetID;
            }
            set
            {
                this.OnLanguageSetIDChanging(value);
                this.ReportPropertyChanging("LanguageSetID");
                this._LanguageSetID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LanguageSetID");
                this.OnLanguageSetIDChanged();
            }
        }
        private global::System.Nullable<int> _LanguageSetID;
        partial void OnLanguageSetIDChanging(global::System.Nullable<int> value);
        partial void OnLanguageSetIDChanged();
        /// <summary>
        /// There are no comments for Property ResourceKeyID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ResourceKeyID
        {
            get
            {
                return this._ResourceKeyID;
            }
            set
            {
                this.OnResourceKeyIDChanging(value);
                this.ReportPropertyChanging("ResourceKeyID");
                this._ResourceKeyID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ResourceKeyID");
                this.OnResourceKeyIDChanged();
            }
        }
        private global::System.Nullable<int> _ResourceKeyID;
        partial void OnResourceKeyIDChanging(global::System.Nullable<int> value);
        partial void OnResourceKeyIDChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
    }
}
